USE [master]
GO
/****** Object:  Database [Java_FinalTest_LongNX]    Script Date: 08/19/2011 09:15:18 ******/
CREATE DATABASE [Java_FinalTest_LongNX] ON  PRIMARY 
( NAME = N'Java_FinalTest_LongNX', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL.1\MSSQL\DATA\Java_FinalTest_LongNX.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Java_FinalTest_LongNX_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL.1\MSSQL\DATA\Java_FinalTest_LongNX_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 COLLATE SQL_Latin1_General_CP1_CI_AS
GO
EXEC dbo.sp_dbcmptlevel @dbname=N'Java_FinalTest_LongNX', @new_cmptlevel=90
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Java_FinalTest_LongNX].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Java_FinalTest_LongNX] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Java_FinalTest_LongNX] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Java_FinalTest_LongNX] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Java_FinalTest_LongNX] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Java_FinalTest_LongNX] SET ARITHABORT OFF 
GO
ALTER DATABASE [Java_FinalTest_LongNX] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Java_FinalTest_LongNX] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [Java_FinalTest_LongNX] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Java_FinalTest_LongNX] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Java_FinalTest_LongNX] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Java_FinalTest_LongNX] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Java_FinalTest_LongNX] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Java_FinalTest_LongNX] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Java_FinalTest_LongNX] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Java_FinalTest_LongNX] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Java_FinalTest_LongNX] SET  ENABLE_BROKER 
GO
ALTER DATABASE [Java_FinalTest_LongNX] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Java_FinalTest_LongNX] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Java_FinalTest_LongNX] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Java_FinalTest_LongNX] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Java_FinalTest_LongNX] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Java_FinalTest_LongNX] SET  READ_WRITE 
GO
ALTER DATABASE [Java_FinalTest_LongNX] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Java_FinalTest_LongNX] SET  MULTI_USER 
GO
ALTER DATABASE [Java_FinalTest_LongNX] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Java_FinalTest_LongNX] SET DB_CHAINING OFF 